### PR TITLE
issue/335 Add Hotgraphic styling for visited icon

### LINKED ISSUE #335: Add styling for Hotgraphic grid checkmark
Add styling to theme for the following Hotgraphic PR: https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/233

### PR DESCRIPTION
**Pull request by swashbuck**
Resolves #335 

Adds Hotgraphic styling for https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/233

hotgraphic-tile-visited

### CODE REVIEW

**Review by guywillis — COMMENTED** [review]
Could you amend the selector to appear on a single line rather than spread across three please?

**Comment by swashbuck** [comment]
> Could you amend the selector to appear on a single line rather than spread across three please?

Done.

**Review by eleanor-heath — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]
Tested locally with FW v5.20.0, all working/displaying as expected.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👍

**Pull request merged**
