### PR TITLE
ABU-779

### PR DESCRIPTION
**Pull request by lc-thomasberger**
forward and back arrows arrows are allways visible.
if this is not by design, then this PR will solve the Issue.

changed themes narrative.less so that narrative-hidden class is not overwritten.

### CODE REVIEW

**Comment by kirsty-hames** [comment]
+1 maybe this should go in the component? This class is added within the component js so there must have been intention to hide these.

**Comment by zenduo** [comment]
I agree with Kirsty, should go in the component.

**Comment by lc-thomasberger** [comment]
good point. so do we need this PR still? (i think "narrative_focus_fix" will do the job)

**Comment by kirsty-hames** [comment]
I think we can cancel this PR. Instead put the fix in for the narrative component and open a new PR.

**Pull request closed without merging**
