### PR TITLE
Accessibility - Fixed drawer template

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by moloko** [comment]
should it not be 
```
_globals._accessibility._ariaLabels
```
?

**Comment by oliverfoster** [comment]
No, I've got to fix that later, the drawer, notify and some other mechanisms all work like this because these items don't have their own model: https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/views/navigationView.js#L34

**Comment by moloko** [comment]
+1 in that case

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
