### PR TITLE
img zoom enable class added

### PR DESCRIPTION
**Pull request by guywillis**
https://github.com/adaptlearning/adapt_framework/issues/2615

### CODE REVIEW

**Comment by guywillis** [comment]
Hi @cahirodoherty-learningpool,

It is intentional as it allows us to target the `.has-img-zoom` class specifically at the component level. If the `.has-img-zoom` class didn't have the associated component class then there is a chance all the components on a page would have their img zooms enabled if a user were to add a zoom effect to the box menu item via the contentObject class field.

```
.accordion {
  .accordion.has-img-zoom &__item-image-container {
    .img-zoom();
  }
}
```

compiles as 

```
.accordion.has-img-zoom .accordion__item-image-container {
 // code here
}
```

**Comment by cahirodoherty-learningpool** [comment]
Hi Guys, thanks for your reply. I understand now the CSS that gets compiled.
One thing I would like to suggest is perhaps replacing the inner `.accordion` with an ampersand? To me, at least, this would prove more readable and consistent with the less as-is.

e.g.:
```
.accordion {
  &.has-img-zoom &__item-image-container {
    .img-zoom();
  }
}
```

**Comment by guywillis** [comment]
Agreed, I'll make the changes across the PRs

**Comment by guywillis** [comment]
@cahirodoherty-learningpool Amends have been made. The only exception is hotgraphic due to the `.hotgraphic` class being applied at the notify level

**Comment by cahirodoherty-learningpool** [comment]
> Agreed, I'll make the changes across the PRs

Thanks Guy. A little pedantic, I know, but I think it looks better now 👍

**Pull request merged**
