### PR TITLE
preview image for AT theme preview

### PR DESCRIPTION
**Pull request by canstudios-louisem**
Preview image for https://github.com/adaptlearning/adapt_authoring/pull/1692

### CODE REVIEW

**Comment by canstudios-louisem** [comment]
We do I think they came from https://unsplash.com/. Would you prefer something like http://i.imgur.com/81jl8rs.jpg that is just a screenshot out of vanilla?

**Comment by moloko** [comment]
Sorry for the slow response. If you can be sure the images came from unsplash and are definitely royalty-free/creative commons/similar then this is absolutely fine to use as-is

**Comment by canstudios-louisem** [comment]
Yep they are the licence is [here](https://unsplash.com/license)

**Comment by tomgreenfield** [comment]
Personally would prefer a screenshot as in Louise's comment above (looks like there's a custom component and non-standard colours in the mock-up).

**Comment by moloko** [comment]
closing due to lack of follow up

**Pull request closed without merging**
