### PR TITLE
modified to resolve issue #1073

### PR DESCRIPTION
**Pull request by chetan-hajare**

### CODE REVIEW

**Comment by chetan-hajare** [comment]
The issue is actually https://github.com/adaptlearning/adapt_framework/issues/1073 not 1037

**Comment by taylortom** [comment]
Is there any need for a disabled (but still visible) feedback button?

**Comment by chetan-hajare** [comment]
Yes. when "_canShowFeedback" is set to true in assessment extension, it is needed to keep the feedback button disabled until submit button is clicked.
when "_canShowFeedback" is set to false, the submit button will occupy the full width and feedback button will not be visible.

**Comment by moloko** [comment]
works for me in IE8, IE11, Firefox, Chrome and iOS 9

I wonder if `buttons-action-fullwidth` would be a better class name though?

**Comment by brian-learningpool** [comment]
It feels a bit like too much of the `_canShowFeedback` logic here is in the Handlebars template.

Would this work better in the core as an updated to `buttonsView.js` in an `addClass()` call.

**Comment by moloko** [comment]
@brian-learningpool seems OK to me in that there's no more complex logic going on here that in any other handlebars template... quite a bit less than some, in fact ;-)

**Comment by moloko** [comment]
Although... now I think about it I see what you're saying. If we do this in the theme then every theme has to include this logic where really it should just be handling the styling. Adding the class via JavaScript probably _is_ the better way to go in this instance.

**Comment by chetan-hajare** [comment]
The changes has to be in core framework not in theme so this pull request is invalid. I will make the changes in framework and raise the new pull request.

**Comment by brian-learningpool** [comment]
Thanks @chetan-hajare.  I think your `buttons.less` changes were probably ok though?

**Comment by chetan-hajare** [comment]
@brian-learningpool  - Do you mean to say css changes must be in theme's buttons.less and js code must be in frameworks's buttonView.js?

**Comment by brian-learningpool** [comment]
Yes, the adding of the class should happen in buttonView.js, but the CSS changes were fine where there were.

**Comment by chetan-hajare** [comment]
created a new PR - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/194

**Pull request closed without merging**
