### PR TITLE
Test folder has been removed.

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**

### CODE REVIEW

**Comment by moloko** [comment]
Travis CI building failing because you need to remove karma.conf.js as well

**Comment by oliverfoster** [comment]
@belal-almassri-spongeuk you'l need to remove karma.conf.js and the scripts>karma attribute from the package.json on all of these prs.

**Comment by belal-almassri-spongeuk** [comment]
Cool I will do it now.

**Comment by moloko** [comment]
Himanshu has written a good summary of what exactly needs removing here: https://github.com/adaptlearning/adapt-contrib-gmcq/pull/74#issuecomment-119163026

**Comment by belal-almassri-spongeuk** [comment]
Thanks a lot @moloko.

**Comment by belal-almassri-spongeuk** [comment]
I have created a new pull request so I am closing this

**Pull request closed without merging**
