### PR TITLE
Fixes ABU-534

### PR DESCRIPTION
**Pull request by tomgreenfield**
Re-exported fonts from IcoMoon.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Tested now?

**Comment by tomgreenfield** [comment]
Tested on IE8–11, Chrome, Firefox, Opera, iOS 7, iOS 7.1, iOS 8.1 & Android 4.3.

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
