### PR TITLE
ABU-1004

### PR DESCRIPTION
**Pull request by lc-thomasberger**
hides marking of question components in assessment

### CODE REVIEW

**Comment by oliverfoster** [comment]
Did you not want to make this part of the assessment code? It seems sensible to have this feature in the extension.

**Comment by lc-thomasberger** [comment]
the reason why I added it to the theme is because you have to add the assessment class by hand to the assessment page.

**Comment by oliverfoster** [comment]
yea, i get that. 

i'm suggesting do this the standard way, having a switch in the authoring tool on the assessment article called _questions._canShowMarking: t/f ?  

that way people don't need to worry about class names or where to put them, just 'can the assessment questions show marking?' tick/untick.

**Comment by lc-thomasberger** [comment]
Should work with all the question components since the class names for "buttons-marking-icon", "icon-tick" and "icon-cross" are used for every question component (at least tho ones used in the test package).
Will close this PR and add the styles to assessment.less.

**Comment by taylortom** [comment]
+1

@oliverfoster I said to implement it this as we don't have time to do this properly prior to release - have added a JIRA feature request.

**Pull request closed without merging**
