### PR TITLE
add option to background-image size

### LINKED ISSUE #301: add '100% 100%' as background-image size option
Proposing that we add '100% 100%' to the AT schema as an option for background-image size.

Current options in schema are 'auto', 'cover', and 'contain'. CSS also allows percentages. '100% 100%' stretches the image to fill the space. It will distort images whose dimensions are not in the same ratio; but is helpful for graphic content that can bear it. Works especially well with SVGs. Without this option in the AT, background-image size must be specified in the uploaded theme or in Custom CSS/LESS code.

### PR DESCRIPTION
**Pull request by chucklorenz**
closes #301

Adds "100% 100%" to schemas, amends help in schemas, amends README.

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👀  Looks great, thanks Chuck.

**Comment by guywillis** [comment]
Would you mind also creating a PR for the boxmenu to do the same thing? https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/master/properties.schema#L79

I think the version could be bumped too 5.7.2 rather than 5.8.0 as it's a small addition rather than new feature.

**Comment by chucklorenz** [comment]
Yes, @guywillis, I can do the same for boxMenu.

**Review by kirsty-hames — CHANGES_REQUESTED** [review]
Looks good thanks but I agree with bumping version to 5.7.2 rather than 5.8.0.

**Review by kirsty-hames — APPROVED** [review]

**Pull request merged**
