### PR TITLE
#2512 with @title-family

### PR DESCRIPTION
**Pull request by simondate**
[#2512](adaptlearning/adapt_framework#2512)
* Add `title-family`

### CODE REVIEW

**Comment by simondate** [comment]
Updated PR with `@title-family`

**Comment by oliverfoster** [comment]
@simondate did you mean to do that?

**Comment by simondate** [comment]
Chuck pointed out there was a merge commit so I was trying to fix it.

**Comment by guywillis** [comment]
@simondate This PR will need to be rebased to `v4-patches` rather than master due to v5 - I have just created this branch for you.

**Comment by oliverfoster** [comment]
is this still needed?

**Comment by simondate** [comment]
I think it's been added to v5 vanilla so probably no.

**Pull request closed without merging**
